### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "ricky.kate@hotmail.com",
    "password": "123456"
}

### Get all users
GET http://localhost:3000/auth/users

### Get user by Id
GET http://localhost:3000/auth/users/4


### Delete user by Id
DELETE http://localhost:3000/auth/users/6

### Update user by ID
PATCH http://localhost:3000/auth/users/4
Content-Type: application/json

{
    "email": "avayah@hotmail.com",
    "password": "0000"
}
